#!/bin/bash

FILE="/sys/class/backlight/rpi_backlight/brightness"

if [ $# = 0 ]; then
	cat ${FILE}
	exit 0
fi

if [ $# -eq 1 ] && [[ $1 =~ ^[0-9]{1,3}$ ]] && [ $1 -ge 0 ] && [ $1 -le 255 ]; then
	echo $1 > ${FILE}
	exit 0
fi

cmd=$( basename $0 )
>&2 echo "USAGE: ${cmd} [ level (0 to 255) ]"
exit 1
